name: Lint Awesome List

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  awesome-lint:
    name: Run awesome-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install awesome-lint
        run: npm install -g awesome-lint
      - name: Lint README
        run: awesome-lint
